services:
  db:
    image: postgres:18.3-bookworm
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: women_couture
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d women_couture"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
